boarddiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from boards import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BoardListView.as_view(), name='home'),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls'))
]

boards/urls.py
from django.urls import path
from boards import views
app_name='boards'
urlpatterns = [
    path('<int:board_id>/', views.TopicListView.as_view(), name='board_topics'),
    path('<int:board_pk>/new/', views.new_topic, name='new_topic'),
    path('<int:board_pk>/topics/<int:topic_pk>/', views.PostListView.as_view(), name='topic_posts'),
    path('<int:board_pk>/topics/<int:topic_pk>/reply/', views.topic_reply, name='topic_reply'),
    path('<int:board_pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

boards/models.py
import math
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator
from django.utils.html import mark_safe
from markdown import markdown


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_total_number_post(self):
        return Post.objects.filter(topic__board=self).count()
    
    def get_lastest_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()
    
    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.subject
        
    def get_page_count(self):
        count = self.posts.count()
        pages = count / 20
        return math.ceil(pages)
    
    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6
        
    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE)
    
    def __str__(self):
        truncated_msg = Truncator(self.message)
        return truncated_msg.chars(50)
    
    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

boards/forms.py
from django import forms
from . models import Topic, Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'placeholder': 'What is on your mind?'}), 
        max_length=4500,
        help_text='The max length of the text is 4500.')
    
    class Meta:
        model = Topic
        fields = ['subject', 'message']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']
    

boards/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.db.models import Count
from django.views.generic import UpdateView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from boards.models import Board, Post, Topic
from . forms import NewTopicForm, PostForm


# def home(request):
#     boards = Board.objects.all()
#     return render(request, 'home/home.html', {'boards':boards})

class BoardListView(ListView):
    model = Board
    context_object_name = 'boards'
    template_name = 'home/home.html'


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'boards/topics.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('board_id'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset
        
class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'boards/topic_posts.html'
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        self.topic.views += 1
        self.topic.save()
        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)
    
    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('board_pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset
        
@login_required
def new_topic(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        topic_form = NewTopicForm(request.POST)
        if topic_form.is_valid():
            topic = topic_form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            Post.objects.create(message=topic_form.cleaned_data.get('message'), 
                    topic=topic, created_by=request.user
                    )
            return redirect('boards:topic_posts', board_pk=board.pk, topic_pk=topic.pk)
    else:
        topic_form = NewTopicForm()
    return render(request, 'boards/new_topic.html', {'board':board, 'topic_form':topic_form})


@login_required
def topic_reply(request, board_pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=board_pk, pk=topic_pk)
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            topic.last_updated = timezone.now() 
            topic.save()
            topic_url = reverse('boards:topic_posts', kwargs={'board_pk': board_pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )

            return redirect(topic_post_url)
    else:
       post_form = PostForm()
    return render(request, 'boards/reply_topic.html', {'topic': topic, 'post_form': post_form})

@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ['message',]
    template_name = 'boards/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)
    
    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('boards:topic_posts', board_pk=post.topic.board.pk, topic_pk=post.topic.pk)
    
    

boards/templates/boards/edit_post.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto mt-2">
             <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
              <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
              <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
              <li class="breadcrumb-item active">Edit post</li>
              </ol>
            </nav>
              <form method="post" class="mb-4" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' with form=form %}
                <button type="submit" class="btn btn-success">Save changes</button>
                <a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
          </form>
        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>    
  var simplemde = new SimpleMDE();
  </script>
{% endblock %}

boards/templates/boards/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-7 mt-5 mx-auto">
            <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><strong><a href="{% url 'home' %}">Boards</a></strong></li>
                    <li class="breadcrumb-item"><a href="{%url 'boards:board_topics' board_id=board.id %}"></a> {{board.name}}</li>
                    <li class="breadcrumb-item active">New topic</li>
                  </ol>
            </nav>
          <form action="{% url 'boards:new_topic' board_pk=board.id %}" method="post" novalidate>
                {% csrf_token %}
                  {% include 'includes/form.html' with form=topic_form%}
                <button type="submit" class="btn btn-success">Post</button>
          </form>

            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>    
  var simplemde = new SimpleMDE();
  </script>
{% endblock %}

boards/templates/boards/reply_topic.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
              <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
              <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
              <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
              <li class="breadcrumb-item active">Post a reply</li>
              </ol>
              <form action="{% url 'boards:topic_reply' topic.board.pk topic.pk %}" method="post" novalidate>
                {% csrf_token %}
             {% include 'includes/form.html' with form=post_form %}
    <button type="submit" class="btn btn-success mb-2">Post a reply</button>
  </form>

  {% for post in topic.get_last_ten_posts %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at|timesince }} ago</small>
          </div>
        </div>
        {{ post.get_message_as_markdown }}
      </div>
    </div>
  {% endfor %}

        </div>
    </div>
</div>

{% endblock %}
{% block javascript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>    
  var simplemde = new SimpleMDE();
  </script>
{% endblock %}

boards/templates/boards/topic_posts.html
{% extends 'base.html' %}
{% load gravatar %}
{% load humanize %}

{% block title %}Dango Board|{{topic.subject}}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9 mx-auto mt-4">
         <ol class="breadcrumb">
             <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
              <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
              <li class="breadcrumb-item active">{{ topic.subject }}</li>
          </ol>
  <div class="mb-4">
    <a href="{% url 'boards:topic_reply' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in posts %}
    <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100 rounded">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at|naturaltime }}</small>
              </div>
            </div>
            <div class="post-body">
              {{ post.get_message_as_markdown }}
            </div>
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm"
                   role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
    {% include 'includes/pagination.html' %}
        </div>
    </div>
</div>

</div>
 
{% endblock %}

boards/templates/boards/topics.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
  <div class="container">
      <div class="row">
      <div class="col-md-9 mt-5 mx-auto">
      <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><strong><a href="{% url 'home' %}">Boards</a></strong></li>
            <li class="breadcrumb-item active"><a href="{% url 'boards:board_topics' board.id %}">{{board.name}}</a> </li>
          </ol>
    </nav>
  <div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>
    <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        {% url 'boards:topic_posts' board.pk topic.pk as topic_url %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="{{ topic_url }}">{{ topic.subject }}</a>
            </p>
            <small class="text-muted">
              Pages:
              {% for i in topic.get_page_range %}
                <a href="{{ topic_url }}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              {% if topic.has_many_pages %}
              ... <a href="{{ topic_url }}?page={{ topic.get_page_count }}">Last Page</a>
              {% endif %}
            </small>
          </td>
          <td class="align-middle">{{ topic.starter.username }}</td>
          <td class="align-middle">{{ topic.replies }}</td>
          <td class="align-middle">{{ topic.views }}</td>
          <td class="align-middle">{{ topic.last_updated|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'includes/pagination.html' %}
        </div>
      </div>
    </div>
{% endblock %}