accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
app_name='accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.password_reset,
         {'template_name': 'accounts/password_reset_form.html',
          'email_template_name': 'accounts/password_reset_email.html',
          'subject_template_name': 'accounts/password_reset_subject.txt',
          'post_reset_redirect': 'accounts:password_reset_done'},
    name='password_reset'),
    path('reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
        path('reset/<uidb64>/<token>/', auth_views.password_reset_confirm,
         {'template_name': 'accounts/password_reset_confirm.html',
          'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('settings/password/change/', auth_views.password_change,{'template_name': 'accounts/password_change.html', 'post_change_redirect': 'accounts:password_change_done'}, name='password_change' ),
    path('settings/password/change/done', auth_views.password_change_done, {'template_name': 'accounts/password_change_done.html'}, name='password_change_done'),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account')
    ]

boarddiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from boards import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BoardListView.as_view(), name='home'),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls'))
]

boards/urls.py
from django.urls import path
from boards import views
app_name='boards'
urlpatterns = [
    path('<int:board_id>/', views.TopicListView.as_view(), name='board_topics'),
    path('<int:board_pk>/new/', views.new_topic, name='new_topic'),
    path('<int:board_pk>/topics/<int:topic_pk>/', views.PostListView.as_view(), name='topic_posts'),
    path('<int:board_pk>/topics/<int:topic_pk>/reply/', views.topic_reply, name='topic_reply'),
    path('<int:board_pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    first_name = forms.CharField(max_length=255, required=True)
    last_name = forms.CharField(max_length=255, required=True)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name','email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from . forms import RegistrationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def register(request):
    if request.method == "POST":
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            return redirect('home')
    else:
        register_form = RegistrationForm()
    return render(request, 'accounts/register.html', {'register_form': register_form})

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'accounts/my_account.html'
    success_url = reverse_lazy('accounts:my_account')

    def get_object(self):
        return self.request.user

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block title %}Dango Board|Login{% endblock %}
{% block content %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
             {% include 'includes/form.html' with form=form %}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            New to Django Boards? <a href="{% url 'accounts:register' %}">Register</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="{% url 'accounts:password_reset' %}" class="text-muted font-weight-bold">Forgot your password?</a>
          </small>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/my_account.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10 mx-auto mt-2">
    <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
             <li class="breadcrumb-item active">My account</li>
          </ol>
    </nav>
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' with form=form %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-6 mx-auto mt-2">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item active font-weight-bold">Change password</li>
  </ol>
</nav>
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto mt-2">
           <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item active font-weight-bold">Change password</li>
  </ol>
</nav>
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a> 
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 mt-2">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' with form=form %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-4 mt-2">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h5 class="card-title lead">Change password for @{{ form.user.username }}</h5>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' with form=form%}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 mt-2">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' with form=form %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block css %}
 <link rel="stylesheet" href="{% static 'css/account.css' %}" type="text/css" />
{% endblock %}
{% block title %}Django Board|Register{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto mt-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center">Register</h5>
        <form action = "{% url 'accounts:register' %}" method="POST" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' with form=register_form %}
            <div class="text-center">
                <button type="submit" class="btn btn-success w-75 ">Register</button>
            </div>
        </form>
        </div>
         <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
          </div>
        </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}